cache:
  directories:
    - "node_modules"

language: node_js
node_js:
- "8"

script:
  - npm run lint
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  target_branch: master
  on:
    branch: develop

branches:
  except:
    - master
