cache:
  directories:
    - "node_modules"

language: node_js
node_js:
- "stable"

script:
  - npm run lint
  - npm run build
  - npm run deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  target_branch: master

branches:
  except:
    - master
